# command line: main.py recognition -c config/st_gcn/kinetics-skeleton/test.yaml --device 0 --num_worker 0 --save_interval 1

base_lr: 0.01
batch_size: 256
config: config/st_gcn/kinetics-skeleton/test.yaml
debug: false
device:
- 0
eval_interval: 5
feeder: feeder.feeder.Feeder
ignore_weights: []
log_interval: 100
model: net.st_gcn.Model
model_args:
    edge_importance_weighting: true
    graph_args:
        layout: openpose
        strategy: spatial
    in_channels: 3
    num_class: 400
nesterov: true
num_epoch: 80
num_worker: 0
optimizer: SGD
pavi_log: false
phase: test
print_log: true
save_interval: 1
save_log: true
save_result: false
show_topk:
- 1
- 5
start_epoch: 0
step: []
test_batch_size: 32
test_feeder_args:
    data_path: ./data/Kinetics/kinetics-skeleton/val_data.npy
    label_path: ./data/Kinetics/kinetics-skeleton/val_label.pkl
train_feeder_args: {}
use_gpu: true
weight_decay: 0.0001
weights: ./models/kinetics-st_gcn.pt
work_dir: ./work_dir/tmp
